routes/admin.php
<?php

Route::group(['middleware' => 'web'], function() {

    Route::group(['as' => 'admin.', 'prefix' => 'admin'], function(){

        Route::get('important/constants', 'ApplicationController@list_of_constants');

        Route::get('clear-cache', function() {

            $exitCode = Artisan::call('config:cache');

            return back();

        })->name('clear-cache');

        Route::get('login', 'Auth\AdminLoginController@showLoginForm')->name('login');

        Route::post('login', 'Auth\AdminLoginController@login')->name('login.post');

        Route::get('logout', 'Auth\AdminLoginController@logout')->name('logout');

        /***
         *
         * Admin Account releated routes
         *
         */

        Route::get('profile', 'AdminController@profile')->name('profile');

        Route::post('profile/save', 'AdminController@profile_save')->name('profile.save');

        Route::post('change/password', 'AdminController@change_password')->name('change.password');


        Route::get('/password/reset','Auth\AdminLoginController@showLinkRequestForm')->name('password.request');

        Route::post('forgot_password_update', 'Auth\AdminLoginController@forgot_password_update')->name('forgot_password.update');
    
        Route::post('reset_password_update', 'Auth\AdminLoginController@reset_password_update')->name('reset_password.update');
    
        Route::get('/reset/password', 'Auth\AdminLoginController@reset_password')->name('reset_password');


        Route::get('/', 'AdminController@index')->name('dashboard');
        
        Route::get('users', 'AdminController@users_index')->name('users.index');

        Route::get('users/create', 'AdminController@users_create')->name('users.create');

        Route::get('users/edit', 'AdminController@users_edit')->name('users.edit');

        Route::post('users/save', 'AdminController@users_save')->name('users.save');

        Route::get('users/view', 'AdminController@users_view')->name('users.view');

        Route::get('users/delete', 'AdminController@users_delete')->name('users.delete');

        Route::get('users/status', 'AdminController@users_status')->name('users.status');

        Route::get('users/verify', 'AdminController@users_verify_status')->name('users.verify');

        Route::get('users/meetings_clear', 'AdminController@users_meetings_clear')->name('users.meetings_clear');

        Route::post('users/bulk_action', 'AdminController@users_bulk_action')->name('users.bulk_action');


        // settings

        Route::get('/admin-control', 'AdminController@admin_control')->name('control');

        Route::get('/ios-control', 'AdminController@ios_control')->name('ios-control'); 

        Route::get('settings', 'AdminController@settings')->name('settings'); 

        Route::post('settings/save', 'AdminController@settings_save')->name('settings.save'); 

        Route::post('env_settings','AdminController@env_settings_save')->name('env-settings.save');

        // STATIC PAGES

        Route::get('static_pages' , 'AdminController@static_pages_index')->name('static_pages.index');

        Route::get('static_pages/create', 'AdminController@static_pages_create')->name('static_pages.create');

        Route::get('static_pages/edit', 'AdminController@static_pages_edit')->name('static_pages.edit');

        Route::post('static_pages/save', 'AdminController@static_pages_save')->name('static_pages.save');

        Route::get('static_pages/delete', 'AdminController@static_pages_delete')->name('static_pages.delete');

        Route::get('static_pages/view', 'AdminController@static_pages_view')->name('static_pages.view');

        Route::get('static_pages/status', 'AdminController@static_pages_status_change')->name('static_pages.status');

        Route::get('/subscriptions', 'AdminController@subscriptions_index')->name('subscriptions.index');

        // Route::get('/subscription/save', 'AdminController@users_subscriptions_save')->name('users.subscriptions.save');

        Route::get('/subscriptions/create', 'AdminController@subscriptions_create')->name('subscriptions.create');

        Route::get('/subscriptions/edit', 'AdminController@subscriptions_edit')->name('subscriptions.edit');

        Route::post('/subscriptions/create', 'AdminController@subscriptions_save')->name('subscriptions.save');

        Route::get('/subscriptions/view', 'AdminController@subscriptions_view')->name('subscriptions.view');

        Route::get('/subscriptions/delete', 'AdminController@subscriptions_delete')->name('subscriptions.delete');

        Route::get('/subscriptions/status', 'AdminController@subscriptions_status_change')->name('subscriptions.status');

        Route::get('/subscriptions/popular/status', 'AdminController@subscriptions_popular_status')->name('subscriptions.popular.status');

        Route::get('/subscriptions/users', 'AdminController@subscriptions_users')->name('subscriptions.users');

        Route::get('subscriptions/payments' , 'AdminController@subscription_payments')->name('subscription.payments');

        Route::get('meetings' , 'AdminController@meetings_index')->name('meetings.index');

        Route::get('meetings/view', 'AdminController@meetings_view')->name('meetings.view');
       
        Route::get('meetings/delete', 'AdminController@meetings_delete')->name('meetings.delete');
        
        Route::get('meetings/end', 'AdminController@meetings_end')->name('meetings.end');
        
        Route::post('meetings/bulk_action_delete', 'AdminController@meetings_bulk_action_delete')->name('meetings.bulk_action.delete');


        //User Subscriptions

        Route::get('/users/subscriptions/', 'AdminController@users_subscriptions_index')->name('users.subscriptions');

        Route::get('/users/subscriptions/save', 'AdminController@users_subscriptions_save')->name('users.subscriptions.save');

        Route::get('/users/subscriptions/view' , 'AdminController@user_subscriptions_view')->name('users.subscriptions.view');


    });

});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/cron_clear_meetings', 'ApplicationController@cron_clear_meetings');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

use Setting, DB;

use App\Helpers\Helper;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * Scope a query to only include active users.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeCommonResponse($query) {

        return $query->select(
            'users.id as user_id',
            'users.username as username',
            'users.name',
            'users.email as email',
            'users.picture as picture',
            'users.description as description',
            'users.mobile as mobile',
            'users.token as token',
            'users.token_expiry as token_expiry',
            'users.social_unique_id as social_unique_id',
            'users.login_by as login_by',
            'users.payment_mode',
            'users.user_card_id',
            'users.status as user_status',
            'users.email_notification_status',
            'users.push_notification_status',
            'users.is_verified as is_email_verified',
            'users.user_type',
            'users.registration_steps',
            'users.created_at',
            'users.updated_at'
            );
    
    }

    /**
     * Scope a query to only include active users.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeOtherCommonResponse($query) {

        return $query->select(
            'users.id as user_id',
            'users.username as username',
            'users.name',
            'users.email as email',
            'users.picture as picture',
            'users.mobile as mobile',
            'users.description as description',
            'users.full_address as full_address',
            'users.work',
            'users.school',
            'users.languages',
            'users.social_unique_id as social_unique_id',
            'users.status as user_status',
            'users.is_verified',
            'users.user_type',
            DB::raw("DATE_FORMAT(users.created_at, '%M %Y') as joined") ,
            'users.created_at',
            'users.updated_at'
            );

    }

    /**
     * Get the UserSubscription record associated with the user.
     */
    public function userSubscription() {
        
        return $this->hasMany(UserSubscription::class, 'user_id');
    }    

    /**
     * Get the Meeting record associated with the user.
     */
    public function userMeeting() {
        
        return $this->hasMany(Meeting::class, 'user_id');
    }

    /**
     * Get the UserCard record associated with the user.
     */
    public function userCard() {
        
        return $this->hasMany(UserCard::class, 'user_id');
    }

    public static function boot() {

        parent::boot();

        static::creating(function ($model) {

            $model->attributes['first_name'] = $model->attributes['last_name'] = $model->attributes['name'];

            $model->attributes['is_verified'] = USER_EMAIL_NOT_VERIFIED;

            // if (Setting::get('is_account_email_verification') == YES && envfile('MAIL_USERNAME') && envfile('MAIL_PASSWORD')) { 

                if($model->attributes['login_by'] == 'manual') {

                    $model->generateEmailCode();

                }

            // }

            $model->attributes['status'] = USER_APPROVED;

            $model->attributes['payment_mode'] = COD;

            $model->attributes['username'] = routefreestring($model->attributes['name']);

            $model->attributes['unique_id'] = uniqid();

            $model->attributes['token'] = Helper::generate_token();

            $model->attributes['token_expiry'] = Helper::generate_token_expiry();

            if(in_array($model->attributes['login_by'], ['facebook' , 'google'])) {
                
                $model->attributes['password'] = \Hash::make($model->attributes['social_unique_id']);
            }

        });

        static::created(function($model) {

            $model->attributes['email_notification_status'] = $model->attributes['push_notification_status'] = YES;

            $model->attributes['unique_id'] = "UID"."-".$model->attributes['id']."-".uniqid();

            $model->save();

            /**
             * @todo Update total number of users 
             */
        
        });

        static::updating(function($model) {

            $model->attributes['username'] = routefreestring($model->attributes['name']);

            $model->attributes['first_name'] = $model->attributes['last_name'] = $model->attributes['name'];

        });

        static::deleting(function ($model){

            Helper::delete_file($model->picture , PROFILE_PATH_USER);

            foreach ($model->userSubscription as $key => $user_subscription) {
                
                $user_subscription->delete();
            }

            foreach ($model->userMeeting as $key => $user_meeting) {
                
                $user_meeting->delete();
            }

            foreach ($model->userCard as $key => $user_card) {
                
                $user_card->delete();
            }

        });

    }

    /**
     * Generates Token and Token Expiry
     * 
     * @return bool returns true if successful. false on failure.
     */

    protected function generateEmailCode() {

        $this->attributes['verification_code'] = Helper::generate_email_code();

        $this->attributes['verification_code_expiry'] = Helper::generate_email_expiry();

        // Check Email verification controls and email configurations

        if(Setting::get('is_account_email_verification') == YES && Setting::get('is_email_notification') == YES && Setting::get('is_email_configured') == YES) {

            $this->attributes['is_verified'] = 0;

        } else { 

            $this->attributes['is_verified'] = 1;
        }

        return true;
    
    }

   
}

resources/views/admin/users/_form.blade.php
<div class="card-body">

    @if(Setting::get('is_demo_control_enabled') == NO )

    <form method="POST" action="{{route('admin.users.save')}}" enctype="multipart/form-data" role="form">

        @else

        <form class="forms-sample" role="form">

            @endif

            @csrf

            <div class="form-body">

                <h3 class="card-title">{{tr('user_info')}}</h3>

                <hr>

                <input type="hidden" name="user_id" value="{{$user_details->id}}">

                <div class="row p-t-20">

                    <div class="form-group col-md-6">

                        <label class="control-label">{{tr('name')}}<span class="admin-required">*</span></label>
                        <input type="text" name="name" value="{{old('name') ?: $user_details->name}}" class="form-control" placeholder="{{tr('name')}}" required>

                    </div>

                    <div class="form-group col-md-6">

                        <label class="control-label">{{tr('email')}}<span class="admin-required">*</span></label>
                        <input type="email" name="email" value="{{old('email') ?: $user_details->email}}" class="form-control" placeholder="{{tr('email')}}" required>

                    </div>

                    @if($user_details->id == null)

                    <div class="form-group col-md-6">

                        <label class="control-label">{{tr('password')}}<span class="admin-required">*</span></label>
                        <input type="password" name="password" value="{{old('password')}}" class="form-control" placeholder="{{tr('password')}}" required>

                    </div>

                    <div class="form-group col-md-6">

                        <label class="control-label">{{tr('confirm_password')}}<span class="admin-required">*</span></label>
                        <input type="password" class="form-control" name="password_confirmation" placeholder="{{tr('confirm_password')}}" value="{{old('confirm_password')}}" required>

                    </div>

                    @endif

                    <div class="form-group col-md-6">

                        <label class="control-label">{{tr('mobile')}}<span class="admin-required">*</span></label>
                        <input type="number" min="1" step="any" class="form-control" name="mobile" value="{{old('mobile') ?: $user_details->mobile}}" placeholder="867676576" required>

                    </div>

                    <div class="form-group col-lg-6 col-md-6">

                        <label for="input-file-now">{{tr('picture')}}</label>
                        <span class="file_input_format_css"> {{tr('upload_files')}}</span>
                        <input type="file" id="input-file-now" name="picture" class="form-control dropify" accept="image/jpeg, image/jpg, image/png" />

                    </div>


                    <div class="form-group col-md-6">

                        <label class="control-label">{{tr('dob')}}<span class="admin-required">*</span></label>
                        <input type="text" name="dob" value="{{old('dob') ?: $user_details->dob}}" class="form-control" placeholder="{{tr('dob')}}" required>

                    </div>

                    <div class="form-group col-md-6">

                        <label class="control-label">{{tr('gender')}}<span class="admin-required">*</span></label>
                        <select class="form-control" name="gender" required>
                            <option value="">{{tr('select')}}</option>
                            <option value="MALE" @if($user_details->gender == MALE) selected @endif>{{tr('male')}}</option>
                            <option value="FEMALE"  @if($user_details->gender == FEMALE) selected @endif>{{tr('female')}}</option>

                        </select>

                    </div>

                </div>

                <div class="row">

                    <div class="form-group col-md-12">

                        <label>{{tr('description')}}</label>

                        <textarea class="form-control" name="description">{{old('description') ?? ($user_details->description ?: "")}}</textarea>

                    </div>


                </div>

            </div>

            <div class="form-actions">

                @if(Setting::get('is_demo_control_enabled') == NO )

                <button type="submit" class="btn btn-primary btn-pill pull-right"> <i class="fa fa-check"></i>{{tr('save')}}</button>

                @else

                <button type="button" class="btn btn-primary btn-pill pull-right"> <i class="fa fa-check"></i>{{tr('save')}}</button>

                @endif

                <button type="reset" class="btn reset-btn btn-pill">{{tr('reset')}}</button>

            </div>

        </form>

</div>

resources/views/admin/users/index.blade.php
@extends('layouts.admin')

@section('page_header',tr('users'))

@section('breadcrumbs')

<li class="breadcrumb-item"><a href="{{route('admin.users.index')}}">{{tr('users')}}</a></li>

<li class="breadcrumb-item active"><a href="javascript:void(0)"></a>{{tr('view_users')}}</li>

@endsection

@section('content')

<div class="card">

    <div class="card-header bg-info">

        <h4 class="m-b-0 text-white">{{tr('view_users')}}

            <button type="button" class="btn btn-secondary" data-toggle="tooltip" data-placement="right" title="{{tr('users_note')}}">{{tr('help')}}</button>
    
            <a class="btn btn-secondary pull-right" href="{{route('admin.users.create')}}">
                <i class="fa fa-plus"></i> {{tr('add_user')}}
            </a>

            <div class="dropdown btn btn-secondary pull-right admin_action">
                <button class="m-b-0 text-white" type="button" id="dropdownMenuOutlineButton1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{tr('admin_bulk_action')}}
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuOutlineButton1">
                    @if(Setting::get('is_demo_control_enabled') == NO)
                    <a class="action_list dropdown-item" id="bulk_delete" href="#">
                        {{tr('delete')}}
                    </a>    
                    @else
                    <a class="dropdown-item" href="javascript:;">{{tr('bulk_delete')}}</a>                           
                    @endif
                    <a class="action_list dropdown-item" id="bulk_approve" href="#">
                        {{tr('approve')}}
                    </a>   
                    <a class="action_list dropdown-item" id="bulk_decline" href="#">
                        {{tr('decline')}}
                    </a>
                    <a class="action_list dropdown-item" id="bulk_meeting_clear" href="#">
                        {{tr('clear_meeting')}}
                    </a>

                </div>
            </div>
        </h4>

    </div>

    <div class="card-body">

        <div class="bulk_action">

                <form  action="{{route('admin.users.bulk_action')}}" id="admin_users" method="POST" role="search">

                    @csrf

                    <input type="hidden" name="action_name" id="action" value="">

                    <input type="hidden" name="selected_users" id="selected_ids" value="">

                    <input type="hidden" name="page_id" id="page_id" value="{{ (request()->page) ? request()->page : '1' }}">

                </form>
            </div>

        @include('admin.users._search')

        <div class="table-responsive">

            @if(count($users) > 0)

                <table id="actionDataTable" class="table data-table">

                    <thead>
                        <tr>
                            <th>
                                <input id="check_all" type="checkbox">
                            </th>
                            <th>{{tr('s_no')}}</th>
                            <th>{{tr('user_name')}}</th>
                            <th>{{tr('image')}}</th>
                            <th>{{tr('email')}}</th>
                            <th>{{tr('mobile')}}</th>
                            <th>{{tr('meetings_clear')}}</th>
                            <th>{{tr('status')}}</th>
                            <th>{{tr('action')}}</th>
                        </tr>
                    </thead>

                    <tbody>

                        @foreach($users as $i => $user_details)
                            
                            <tr>
                                <td><input type="checkbox" name="row_check" class="faChkRnd" id="{{$user_details->id}}" value="{{$user_details->id}}"></td>
                                <td>{{$i+$users->firstItem()}}</td>

                                <td>
                                    <a href="{{ route('admin.users.view', ['user_id' => $user_details->id]) }}">{{$user_details->name}}&nbsp;&nbsp;</a>
                                </td>

                                <td> <img src="{{$user_details->picture ?? asset('placeholder.jpg')}}" alt="user" width="40" class="img-circle" /> </td>

                                <td>
                                    {{$user_details->email}}
                                </td>

                                <td>{{$user_details->mobile ? : tr('na')}}</td>

                                <td>
                                @if($user_details->is_cleared == tr('clear'))

                                <a href="{{route('admin.users.meetings_clear',['user_id'=>$user_details->id])}}" 
                                    onclick="return confirm('Are you sure about ongoing meetings clear?')"
                                >{{$user_details->is_cleared}}
                               </a>

                                @else
                                
                                    <a href="javascript:void(0)">{{$user_details->is_cleared}}</a>
                                @endif
                               </td>

                                <td>
                                    @if($user_details->status ==  YES)
                                        <span class="badge badge-success">{{tr('approved')}}
                                        </span>
                                    @else
                                        <span class="badge badge-danger">{{tr('declined')}}</span> 
                                    @endif
                                </td>

                                <td>
                                    
                                    <div class="dropdown">

                                        <button class="btn btn-outline-primary  dropdown-toggle btn-sm" type="button" id="dropdownMenuOutlineButton1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        {{tr('action')}}
                                        </button>
                                        <div class="dropdown-menu" aria-labelledby="dropdownMenuOutlineButton1">
                                          
                                            <a class="dropdown-item" href="{{ route('admin.users.view', ['user_id' => $user_details->id]) }}">
                                                {{tr('view')}}
                                            </a>
                                            
                                            @if(Setting::get('is_demo_control_enabled') == NO)

                                                <a class="dropdown-item" href="{{ route('admin.users.edit', ['user_id' => $user_details->id]) }}">
                                                    {{tr('edit')}}
                                                </a>
                                                
                                                <a class="dropdown-item" href="{{route('admin.users.delete', ['user_id' => $user_details->id,'page'=>request()->input('page')])}}" 
                                                onclick="return confirm(&quot;{{tr('user_delete_confirmation' , $user_details->name)}}&quot;);">
                                                    {{tr('delete')}}
                                                </a>
                                            @else

                                                <a class="dropdown-item" href="javascript:;">{{tr('edit')}}</a>
                                              
                                                <a class="dropdown-item" href="javascript:;">{{tr('delete')}}</a>                           
                                            @endif
                                            
                                            <div class="dropdown-divider"></div>

                                            @if($user_details->is_verified == USER_EMAIL_NOT_VERIFIED) 

                                                <a class="dropdown-item" href="{{ route('admin.users.verify', ['user_id' => $user_details->id]) }}"> {{ tr('verify') }} 
                                                </a>

                                            @endif 

                                            @if($user_details->status == USER_APPROVED)

                                                <a class="dropdown-item" href="{{ route('admin.users.status', ['user_id' => $user_details->id]) }}" onclick="return confirm(&quot;{{$user_details->first_name}} - {{tr('user_decline_confirmation')}}&quot;);" >
                                                    {{ tr('decline') }} 
                                                </a>

                                            @else
                                                
                                                <a class="dropdown-item" href="{{ route('admin.users.status', ['user_id' => $user_details->id]) }}">
                                                    {{ tr('approve') }} 
                                                </a>
                                                   
                                            @endif

                                            <a class="dropdown-item" href="{{ route('admin.meetings.index', ['user_id' => $user_details->id]) }}">
                                                {{ tr('meetings') }} 
                                            </a>

                                            <a class="dropdown-item" href="{{ route('admin.users.subscriptions' , ['user_id' => $user_details->id] ) }}">       
                                                {{ tr('subscription_plans') }}
                                            </a>


                                        </div>

                                    </div>

                                </td>
                             
                            </tr>
                        @endforeach
                       
                    </tbody>
                    
                </table>

                <div class="pull-right pt-5">{{ $users->appends(request()->input())->links() }}</div>

            @else

                <h3 class="no-result text-center pt-5">{{ tr('no_user_found') }}</h3>
                
            @endif

        </div>
        
    </div>
    
</div>

@endsection

@section('scripts')
    
@if(Session::has('bulk_action'))
<script type="text/javascript">
    $(document).ready(function(){
        localStorage.clear();
    });
</script>
@endif

<script type="text/javascript">

    $(document).ready(function(){
        get_values();

        $('.action_list').click(function(){
            var selected_action = $(this).attr('id');
            if(selected_action != undefined){
                $('#action').val(selected_action);
                if($("#selected_ids").val() != ""){
                    if(selected_action == 'bulk_delete'){
                        var message = "<?php echo tr('admin_user_delete_confirmation') ?>";
                    }else if(selected_action == 'bulk_approve'){
                        var message = "<?php echo tr('admin_users_approve_confirmation') ?>";
                    }else if(selected_action == 'bulk_decline'){
                        var message = "<?php echo tr('admin_users_decline_confirmation') ?>";
                    }else if(selected_action == 'bulk_meeting_clear'){
                        var message = "<?php echo tr('admin_meeting_clear_confirmation') ?>";
                    }
                    var confirm_action = confirm(message);

                    if (confirm_action == true) {
                      $( "#admin_users" ).submit();
                    }
                    // 
                }else{
                    alert('Please select the check box');
                }
            }
        });
    // single check
    var page = $('#page_id').val();
    $(':checkbox[name=row_check]').on('change', function() {
        var checked_ids = $(':checkbox[name=row_check]:checked').map(function() {
            return this.id;
        })
        .get();

        localStorage.setItem("user_checked_items"+page, JSON.stringify(checked_ids));

        get_values();

    });
    // select all checkbox
    $("#check_all").on("click", function () {
        if ($("input:checkbox").prop("checked")) {
            $("input:checkbox[name='row_check']").prop("checked", true);
            var checked_ids = $(':checkbox[name=row_check]:checked').map(function() {
                return this.id;
            })
            .get();

            localStorage.setItem("user_checked_items"+page, JSON.stringify(checked_ids));
            get_values();
        } else {
            $("input:checkbox[name='row_check']").prop("checked", false);
            localStorage.removeItem("user_checked_items"+page);
            get_values();
        }

    });


    function get_values(){
        var pageKeys = Object.keys(localStorage).filter(key => key.indexOf('user_checked_items') === 0);
        var values = Array.prototype.concat.apply([], pageKeys.map(key => JSON.parse(localStorage[key])));

        if(values){
            $('#selected_ids').val(values);
        }

        for (var i=0; i<values.length; i++) {
            $('#' + values[i] ).prop("checked", true);
        }

}

});
</script>
@endsection